[project]
authors = [
    {name = "Yurasov Aleksey", github = "https://github.com/YurasovAleksey"},
]
name = "hexlet-code"
version = "0.1.0"
description = "Page analyzer project"
readme = "README.md"
requires-python = ">=3.9"
dependencies = []
